config/routes.rb
Mihimihi::Application.routes.draw do
  

  devise_for :users

  namespace :admin do
    resources :events
    resources :image_data
  end
  resources :events, :only => [:index]
  root :to => 'public#mihimihi'
end

app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessible :content, :title, :years_ago, :over_time, :lonlat, :large_icon_url, :image, :summary

  mount_uploader :image, ImageUploader
end

app/models/image_datum.rb
class ImageDatum < ActiveRecord::Base
  attr_accessible :image, :link, :title, :years_ago
  mount_uploader :image, ImageUploader
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_filter :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @event.lonlat = '{"type": "LineString", "coordinates": [[x1, y1], [x2, y2]]}'
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end 
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to admin_events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin/image_data_controller.rb
class Admin::ImageDataController < ApplicationController
  before_filter :authenticate_user!

  # GET /image_data
  # GET /image_data.json
  def index
    @image_data = ImageDatum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @image_data }
    end
  end

  # GET /image_data/1
  # GET /image_data/1.json
  def show
    @image_datum = ImageDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image_datum }
    end
  end

  # GET /image_data/new
  # GET /image_data/new.json
  def new
    @image_datum = ImageDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image_datum }
    end
  end

  # GET /image_data/1/edit
  def edit
    @image_datum = ImageDatum.find(params[:id])
  end

  # POST /image_data
  # POST /image_data.json
  def create
    @image_datum = ImageDatum.new(params[:image_datum])

    respond_to do |format|
      if @image_datum.save
        format.html { redirect_to admin_image_datum_path(@image_datum), notice: 'Image datum was successfully created.' }
        format.json { render json: @image_datum, status: :created, location: @image_datum }
      else
        format.html { render action: "new" }
        format.json { render json: @image_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /image_data/1
  # PUT /image_data/1.json
  def update
    @image_datum = ImageDatum.find(params[:id])

    respond_to do |format|
      if @image_datum.update_attributes(params[:image_datum])
        format.html { redirect_to admin_image_datum_path(@image_datum), notice: 'Image datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_data/1
  # DELETE /image_data/1.json
  def destroy
    @image_datum = ImageDatum.find(params[:id])
    @image_datum.destroy

    respond_to do |format|
      format.html { redirect_to admin_image_data_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all.select{|x| x.years_ago != nil && x.years_ago > 0}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def mihimihi
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/image_data_helper.rb
module ImageDataHelper
end

app/views/admin/events/_form.html.haml
- if @event.id != nil
  - url = admin_event_path(@event)
- else
  - url = admin_events_path

= form_for @event, :url => url, :html => {:multipart => true}do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :summary
    = f.text_area :summary, :size => '100x1'
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :years_ago
    = f.text_field :years_ago
  .field
    = f.label :over_time
    = f.text_field :over_time
  .field
    = f.label :lonlat
    = f.text_area :lonlat
  .field
    = f.label :image
    = f.file_field :image

  .actions
    = f.submit 'Save'

app/views/admin/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', admin_event_path(@event)
\|
= link_to 'Back', admin_events_path

app/views/admin/events/index.html.haml
%h1 Listing events

%table.table.table-striped
  %tr
    %th Title
    %th time
    %th
    %th
    %th

  - @events.sort_by{|x| x.years_ago || 1000000}.each do |event|
    %tr
      %td= event.title
      %td= event.years_ago
      %td= link_to 'Show', admin_event_path(event)
      %td= link_to 'Edit', edit_admin_event_path(event)
      %td= link_to 'Destroy', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Event', new_admin_event_path

app/views/admin/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', admin_events_path

app/views/admin/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Content:
  = @event.content

= link_to 'Edit', edit_admin_event_path(@event)
\|
= link_to 'Back', admin_events_path

app/views/admin/image_data/_form.html.haml
- if @image_datum.id != nil
  - url = admin_image_datum_path(@image_datum)
- else
  - url = admin_image_data_path

= form_for @image_datum, :url => url, :html => {:multipart => true} do |f|
  - if @image_datum.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image_datum.errors.count, "error")} prohibited this image_datum from being saved:"
      %ul
        - @image_datum.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :years_ago
    = f.number_field :years_ago
  .field
    = f.label :image
    = f.file_field :image

  .actions
    = f.submit 'Save'

app/views/admin/image_data/edit.html.haml
%h1 Editing image_datum

= render 'form'

= link_to 'Show', admin_image_data_path(@image_datum)
\|
= link_to 'Back', admin_image_data_path

app/views/admin/image_data/index.html.haml
%h1 Listing image_data

%table.table.table-striped
  %tr
    %th Link
    %th Title
    %th Image
    %th Years ago
    %th
    %th
    %th

  - @image_data.sort_by{|x| x.years_ago || 1000000}.each do |image_datum|
    %tr
      %td
        %a{:href => image_datum.link, :target => '_blank'}
          link
      %td= image_datum.title
      %td
        %img{:src => image_datum.image.icon}
      %td= image_datum.years_ago
      %td= link_to 'Show', admin_image_datum_path(image_datum)
      %td= link_to 'Edit', edit_admin_image_datum_path(image_datum)
      %td= link_to 'Destroy', admin_image_datum_path(image_datum), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Image datum', new_admin_image_datum_path

app/views/admin/image_data/new.html.haml
%h1 New image_datum

= render 'form'

= link_to 'Back', admin_image_data_path

app/views/admin/image_data/show.html.haml
%p#notice= notice

%p
  %b Link:
  = @image_datum.link
%p
  %b Title:
  = @image_datum.title
%p
  %b Image:
  = @image_datum.image
%p
  %b Years ago:
  = @image_datum.years_ago

= link_to 'Edit', edit_admin_image_datum_path(@image_datum)
\|
= link_to 'Back', admin_image_data_path

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Content:
  = @event.content

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin thingi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/public.html.haml
!!!
%html
  %head
    %title= "Mihimihi"
    %meta{name: "description", content: "Mihimihi visualisation by Graham Jenson"}
    %meta{name: "keywords",content: "Mihimihi visualisation mixandmash hashbang"}
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
    //this is here because google stuff inserts above first script element
    %script
%body
  = yield

= render 'shared/google_analytics'
= google_webfonts_link_tag :unica_one, :lato, :strait, :bilbo
%link(href='http://fonts.googleapis.com/css?family=Domine&subset=latin,latin-ext' rel='stylesheet' type='text/css')
%link(href='http://fonts.googleapis.com/css?family=Amatic+SC:700a' rel='stylesheet' type='text/css')
= javascript_include_tag "mihimihimeta"

app/views/shared/_google_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21053562-1']);
  _gaq.push(['_setDomainName', 'mihimihi.maori.geek.nz']);
  _gaq.push(['_trackPageview']);
  (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();